//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR_Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID_sotrudnika { get; set; }
        public string Wamilia { get; set; }
        public string Imia { get; set; }
        public string Otwewto { get; set; }
        public string Passportnii_dannie { get; set; }
        public string Nomer_telewona { get; set; }
        public string Adres { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
        public Nullable<int> Dolwnost { get; set; }
        public string Pol { get; set; }
    
        public virtual Dolwnost Dolwnost1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
