//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR_Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int Kod_tovara { get; set; }
        public string Nazvanie { get; set; }
        public string Kolitewto_upakovok { get; set; }
        public string Thena_za_upakowku { get; set; }
        public Nullable<int> Tip_sklada { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
