//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR_Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozvratnia_tara_Tovar
    {
        public int Kod { get; set; }
        public Nullable<int> Kod_Tovara { get; set; }
        public Nullable<int> Kod_Vozvratnoi_tari { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Vozvratnaia_tara Vozvratnaia_tara { get; set; }
    }
}
