//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR_Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozvratnaia_tara
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozvratnaia_tara()
        {
            this.Vozvratnia_tara_Tovar = new HashSet<Vozvratnia_tara_Tovar>();
        }
    
        public int Nomer_vozvratnoi_tari { get; set; }
        public string Nazvanie_klienta { get; set; }
        public string Kplitewto_upakowok { get; set; }
        public string Ves { get; set; }
        public Nullable<System.DateTime> Data_postavki { get; set; }
        public string Adres_postavki { get; set; }
        public Nullable<int> Sotrudniki { get; set; }
        public string Wtrix_kod { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vozvratnia_tara_Tovar> Vozvratnia_tara_Tovar { get; set; }
    }
}
