//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR_Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Tovar = new HashSet<Tovar>();
        }
    
        public int Nomer_zakaza { get; set; }
        public Nullable<int> Klient { get; set; }
        public string Kplitewto_upakowok { get; set; }
        public string Ves { get; set; }
        public Nullable<System.DateTime> Data_dostavki { get; set; }
        public string Adres_dostavki { get; set; }
        public Nullable<int> Sotrudniki { get; set; }
    
        public virtual Klient Klient1 { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tovar> Tovar { get; set; }
    }
}
